@startuml EquipeCinema

title Diagrama de Classes - Equipes de Cinema

interface Team {
  + void partOf();
}

class Cast implements Team {
  + void partOf();
}

class Crew implements Team {
  + void partOf();
}

class Person {
    - Team team;
    + void setTime(Team team);
    + void partOf();
}

Person *--> Team

@enduml